#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    -----------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    -----------------------------------------------------
#
#    This program is free software: you can redistribute
#    it and/or modify it under the terms of the
#    GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of
#    the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it
#    will be useful, but WITHOUT ANY WARRANTY;
#    without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the GNU Affero General Public License for
#    more details.
#
#    You should have received a copy of the
#    GNU Affero General Public License
#    along with this program.
#    If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
         "env")")"
_lib="$(
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_libevm="${_lib}/libevm/libevm"
_sourced \
  "${_crash_bash}" 2>/dev/null || \
  source \
    "${_crash_bash}"
_sourced \
  "${_libevm}"

# shellcheck disable=SC2034
_global_variables() {
  call_date=""
  call_type=""
  index_retrieve=""
  target_app=""
  target_contract=""
  contract_address=""
  contract_bytecode=""
  contract_compiler_output=""
  contract_abi=""
  contract_method=""
  method_args=()
  price_gas=""
  measure_unit=""
  cache_dir=""
  data_dir=""
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    'libevm-requirements' \
    'libevm'
  libevm-requirements
  _check_cmd \
    "evm-chains-explorers"
  _check_cmd \
    "evm-chains-info"
  _check_cmd \
    'evm-contracts-abi-get'
  _check_cmd \
    'evm-contract-source-get' \
    'evm-contracts-source-index'
  _check_cmd \
    'evm-wallet'
  _check_cmd \
    'node-run'
}

_evm_contract_call_type() {
  local \
    _type="${1}" \
    _lib
  _lib="$(
    _get_lib)/evm-contracts-tools"
  echo \
    "${_lib}/evm-contract-call-${_type}"
}

_artifact_missing_reset() {
  local \
    _type="${1}" \
    _artifact \
    _msg=()
  _artifact="$(
    _get \
      "_contract" \
      "${_type}")"
  if [[ ! -e "${_artifact}" ]]; then
    _msg=(
      "Contract '${_type//_/ }' at"
      "'${_artifact}' does not"
      "exist."
    )
    _msg_info \
      "${_msg[*]}"
    _set \
      "_contract" \
      "${_type}" \
      ""
  fi
}

_contract_address_get() {
  local \
    _target_app \
    _target_contract \
    _target_network \
    _contract_address \
    _evm_contract_deployment_address_opts=()
  _target_app="${target_app}"
  _target_contract="${target_contract}"
  _target_network="${target_network}"
  if (( 0 < "$#" )); then
    _target_app="${1}"
  fi
  if (( 1 < "$#" )); then
    _target_contract="${2}"
  fi
  if (( 2 < "$#" )); then
    _target_contract="${3}"
  fi
  _evm_contract_deployment_address_opts+=(
    -a
      "${_target_app}"
    -n
      "${_target_network}"
  )
  _contract_address="$(
    evm-contract-deployment-address \
      "${_evm_contract_deployment_address_opts[@]}" \
      "${_target_contract}" || \
      true)"
  echo \
    "${_contract_address}"
}

_target_contract_get() {
  local \
    _target_app="${1}" \
    _contract_address="${2}" \
    _target_contract \
    _address_sanity
  _target_contract=""
  _address_sanity="$(
    _address_sanity_check \
      "${contract_address}" \
      0 \
      2>&1)"
  if [[ "${_address_sanity}" == "" ]]; then
    _target_contract="$(
      _contract_lookup_address \
        "${target_app}" \
        0)"
  # else
  fi
  echo \
    "${_target_contract}"
}

_target_app_get() {
  local \
    _contract_address="${1}" \
    _target_app \
    _address_sanity
  _target_app=""
  if [[ "${_contract_address}" != "" ]]; then
    _address_sanity="$(
      _address_sanity_check \
        "${_contract_address}" \
        0 \
        2>&1)"
    if [[ "${_address_sanity}" != "" ]]; then
      _target_app="$(
        _app_lookup_contract \
          "${_contract_address}" \
          0)"
    # else
    fi
  fi
  echo \
    "${_target_app}"
}

_contract_address_auto_detect() {
  local \
    _contract_address \
    _address_sanity \
    _msg=()
  _contract_address=""
  if [[ "${contract_address}" != "" ]]; then
    _address_sanity="$(
      _address_sanity_check \
        "${_contract_address}" \
        0 \
        2>&1)"
    if [[ "${_address_sanity}" != "" ]]; then
      if [[ "${target_app}" != "" && \
            "${target_network}" != "" && \
            "${target_contract}" != "" ]]; then
        _msg=(
          "Looking for address"
          "corresponding to contract"
          "'${_target_contract}' for the"
          "'${target_app}'"
          "libEVM application on network"
          "'${target_network}'."
        )
        _msg_info \
          "${_msg[*]}"
        _contract_address="$(
          _contract_address_get \
            "${target_app}" \
            "${target_contract}" \
            "${target_network}")"
      _set \
        "contract" \
        "address" \
        "${_contract_address}"
      fi
    else
      _msg=(
        "One between the"
        "application '${target_app}',"
        "the network '${target_network}'"
        "or the contract '${target_contract}'"
        "has not been specified."
      )
      _msg_info \
        "${_msg[*]}"
    fi
  fi
}

_target_contract_auto_detect() {
  local \
    _target_contract
  _target_contract=""
  if [[ "${target_app}" != "" ]]; then
    if [[ "${contract_address}" != "" ]]; then
      _target_contract="$(
        _target_contract_get \
          "${target_app}" \
          "${contract_address}")"
    fi
  fi
  _set_override \
    "target" \
    "contract" \
    "${_target_contract}"
}

_target_app_auto_detect() {
  local \
    _target_app \
    _address_sanity
  _target_app=""
  if [[ "${contract_address}" != "" ]]; then
    _target_app="$(
      _target_app_get \
        "${contract_address}")"
  fi
  _set_override \
    "target" \
    "app" \
    "${_target_app}"
}

_artifacts_check() {
  local \
    _msg=()
  _artifact_missing_reset \
    "abi_path"
  _artifact_missing_reset \
    "bytecode_path"
  _artifact_missing_reset \
    "compiler_output_path"
  if [[ "${_contract_compiler_output_path}" == "" ]] && \
     [[ "${_contract_abi_path}" == "" ]]; then
    _msg=(
      "To safely perform an EVM contract call"
      "you have to provide either"
      "the contract ABI or"
      "an Hardhat compilation artifact."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
}

_evm_contract_call() {
  local \
    _call_type="${1}" \
    _call_timeout="${2}" \
    _wallet_name="${3}" \
    _wallet_path="${4}" \
    _wallet_password="${5}" \
    _wallet_seed="${6}" \
    _api_key_path="${7}" \
    _price_gas="${8}" \
    _msg_value="${9}" \
    _measure_unit="${10}" \
    _retries_max="${11}" \
    _network="${12}" \
    _rpc_selection="${13}" \
    _cache_dir="${14}" \
    _data_dir="${15}" \
    _contract_address="${16}" \
    _contract_abi_path="${17}" \
    _contract_bytecode_path="${18}" \
    _contract_compiler_output_path="${19}" \
    _contract_method="${20}" \
    _node_run_opts=() \
    _method_args=() \
    _cmd \
    _args=() \
    _rpc_backend \
    _msg=()
  shift \
    20
  _method_args+=(
    "$@"
  )
  _node_run_opts+=(
    -r
      "${_retries_max}"
  )
  _rpc_backend_get \
    "${_network}" \
    "${_rpc_selection}"
  _cmd="$(
    _evm_contract_call_type \
      "${_call_type}")"
  _artifacts_check
  if [[ "${_call_type}" == "static" ]]; then
    _args+=(
      "${quiet}"
      "${_wallet_seed}"
      "${_retries_max}"
      "${_api_key_path}"
      "${_rpc_backend}"
      "${_contract_abi_path}"
      "${_contract_bytecode_path}"
      "${_contract_compiler_output_path}"
      "${_contract_address}"
      "${_contract_method}"
      "${_method_args[@]}"
    )
  elif [[ "${_call_type}" == "dynamic" ]]; then
    _args+=(
      "${quiet}"
      "${_retries_max}"
      "${_call_timeout}"
      "${_wallet_seed}"
      "${_wallet_password}"
      "${_api_key_path}"
      "${_price_gas}"
      "${_msg_value}"
      "${_measure_unit}"
      "${_rpc_backend}"
      "${_contract_address}"
      "${_contract_abi_path}"
      "${_contract_bytecode_path}"
      "${_contract_compiler_output_path}"
      "${_contract_method}"
      "${_method_args[@]}"
    )
  fi
  _msg=(
    "Calling evm-contract-call-${_call_type}"
    "with arguments '${_args[*]}'."
  )
  _msg_info \
    "${_msg[*]}"
  node-run \
    "${_node_run_opts[@]}" \
    "${_cmd}" \
    "${_args[@]}"
}

# This overrides the LibEVM one
_contract_abi_auto_detect() {
  local \
    _abi \
    _address \
    _compiler_output \
    _key \
    _network \
    _abi_dir
  _network="${target_network}"
  _address="${contract_address}"
  _key="${api_key}"
  _abi="${contract_abi}"
  _compiler_output="${contract_compiler_output}"
  _abi_target="${_abi}"
  if [[ "${_abi_target}" == "" ]]; then
     _abi_target="$(
      _default_artifact_path_get \
        "abi")"
  fi
  _abi_dir="$(
    dirname \
      "${_abi}")"
  if [[ ! -e "${_abi}" ]] && \
     [[ ! -e "${_compiler_output}" ]]; then
    if [[ -e "${_abi_target}" ]]; then
      _abi="${_abi_target}"
    elif [[ ! -e "${_abi_target}" ]]; then
      _contract_artifacts_retrieve \
        "${_abi_dir}"
    fi
  fi
  _set \
    "contract" \
    "abi" \
    "${_abi}"
}

_artifact_type_check() {
  local \
    _type="${1}" \
    _msg=()
  if [[ "${_type}" != "abi" && \
        "${_type}" != "bytecode" && \
        "${_type}" != "compiler-output" ]]; then
    _msg=(
      "Unknown artifact type '${_type}'."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
  true
}

_default_artifact_path_get() {
  local \
    _type="${1}" \
    _app_data_dir \
    _network \
    _address \
    _app \
    _artifact \
    _evm_contract_deployment_artifact_opts=() \
    _msg=()
  if (( 1 < "${#}" )); then
    _app_data_dir="${2}"
  else
    if [[ -v "_data_dir" ]]; then
      _app_data_dir="${_data_dir}"
    elif [[ -v "data_dir" ]]; then
      _app_data_dir="${data_dir}"
    fi
  fi
  if (( 2 < "${#}" )); then
    _network="${3}"
  else
    if [[ -v "_target_network" ]]; then
      _network="${_target_network}"
    elif [[ -v "target_network" ]]; then
      _network="${target_network}"
    fi
  fi
  if (( 3 < "${#}" )); then
    _address="${4}"
  else
    if [[ -v "_contract_address" ]]; then
      _address="${_contract_address}"
    elif [[ -v "contract_address" ]]; then
      _address="${contract_address}"
    fi
  fi
  if (( 4 < "${#}" )); then
    _app="${4}"
  else
    if [[ -v "_target_app" ]]; then
      _app="${_target_app}"
    elif [[ -v "target_app" ]]; then
      _app="${target_app}"
    fi
  fi
  _type="${_type//_/-}"
  _artifact_type_check \
    "${_type}"
  if [[ "${_app}" == "" ]]; then
    _artifact_dir="${_data_dir}/${_network}"
    if [[ "${_type}" == "abi" ]]; then
      _artifact="${_artifact_dir}/${_address}.abi.json"
    elif [[ "${_type}" == "bytecode" ]]; then
      _artifact="${_artifact_dir}/${_address}.bin"
    elif [[ "${_type}" == "compiler-output" ]]; then
      _artifact="${_artifact_dir}/${_address}.json"
    fi
  else
    _evm_contract_deployment_artifact_opts+=(
      -n
        "${_network}"
      -a
        "${_app}"
    )
    _artifact="$(
      "evm-contract-deployment-${_type}" \
        "${_evm_contract_deployment_artifact_opts[@]}" \
        "${_address}")"
  fi
  echo \
    "${_artifact}"
}

# This overrides the LibEVM one
_contract_bytecode_auto_detect() {
  local \
    _bytecode
  _bytecode="$(
    _default_artifact_path_get \
      "bytecode")"
  if [[ ! -e "${_bytecode}" ]]; then
    _bytecode=""
  fi
  _set_override \
    "contract" \
    "bytecode"
    "${_bytecode}"
}

_artifact_local_auto_detect() {
  local \
    _type="${1}" \
    _artifact
  _artifact="$(
    _default_artifact_path_get \
      "${_type}")"
  _set_override \
    "contract" \
    "${_type}" \
    "${_artifact}"
}

_call_auth_auto_detect() {
  local \
    _call_auth
  if [[ "${call_type}" == "static"  ]]; then
    _call_auth="n"
  elif [[ "${call_type}" == "dynamic"  ]]; then
    _call_auth="y"
  fi
  _set_override \
    "call" \
    "auth" \
    "${_call_auth}"
}

_set_overrides() {
  local \
    _abi \
    _bytecode \
    _compiler_output \
    _data_dir \
    _sanity_enforce
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  _override_set \
    "data" \
    "dir" \
    "${HOME}/.local/share/${app_name}"
  _override_set \
    "cache" \
    "dir" \
    "${HOME}/.cache/${app_name}"
  _target_app_auto_detect
  _data_dir="${HOME}/.local/share/${app_name}"
  _set_override \
    "call" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "wallet" \
    "name" \
    "default"
  _set_override \
    "index" \
    "retrieve" \
    "n"
  _set_override \
    "contract" \
    "address" \
    ""
  _set_override \
    "retries" \
    "max" \
    "300"
  _set_override \
    "target" \
    "network" \
    "100"
  _set_override \
    "rpc" \
    "selection" \
    "kirsh"
  _set_override \
    "call" \
    "type" \
    "static"
  _call_auth_auto_detect
  _set_override \
    "call" \
    "timeout" \
    "300000"
  _set_override \
    "measure" \
    "unit" \
    "ether"
  _set_override \
    "price" \
    "gas" \
    ""
  _set_override \
    "msg" \
    "value" \
    "0"
  _api_key_auto_detect \
    "${target_network}"
  _target_contract_auto_detect
  _contract_address_auto_detect
  if [[ "${contract_address}" != "" ]]; then
    if [[ "${target_app}" == "" ]]; then
      _sanity_enforce="1"
      _address_sanity_check \
        "${contract_address}" \
        "${_sanity_enforce}" \
        2>"/dev/null"
    elif [[ "${target_app}" != "" ]]; then
      _sanity_enforce="0"
      _address_sanity_check \
        "${contract_address}" \
        "${_sanity_enforce}" \
        2>"/dev/null"
    fi
    _set_override \
      "contract" \
      "abi" \
      "$(_default_artifact_path_get \
           "abi")"
    _artifact_local_auto_detect \
      "bytecode"
    _artifact_local_auto_detect \
      "compiler_output"
    if [[ "${contract_abi}" == "" ]] || 
       [[ "$(_default_artifact_path_get \
               "abi")" == "${contract_abi}" ]]; then
      _contract_abi_auto_detect
    fi
  fi
  _wallet_overrides_set \
    "evm-wallet" \
    "${wallet_name}" \
    "${call_auth}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _exit_code="${1}" \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Runs a smart contract function.

Usage:
  ${app_name}
    [options]
    <contract-address>
    <contract-method>
    ([method-args])

  arguments:
    contract                  It can be an address (0x...)
                              or a libEVM application contract
                              name.
    contract-method           A contract method (function) name.
    method-args               The method arguments.

  networks:
    All those supported by
    'evm-chains-info' as
    well as directly RPC
    address.

  options:
     -t <call-type>           It can be 'static' or 'dynamic'.
                              Default: ${call_type}

  call options:
     -V <msg-value>           How much '${measure_unit}' attach to the
                              transaction.
                              Default: ${msg_value}
     -u <measure-unit>        Measure unit for the transaction
                              value. It can be 'ether' or 'wei'.
                              Default: ${measure_unit}
     -P <price-gas>           I don't remember what this is.
                              Default: ${price_gas}
     -r <retries-max>         Maximum number of retries before
                              declaring the call failed.
                              Default: ${retries_max}
     -T <call-timeout>        Maximum number of milliseconds before
                              declaring the call failed.
                              Default: ${call_timeout}
  contract options:
     -A <abi>                 Contract ABI path.
                              Default: ${contract_abi}
     -B <bytecode>            Contract bytecode path.
                              Default: ${contract_bytecode}
     -C <compiler-output>     Contract compiler output
                              path (the hardhat artifact).
                              Default: ${contract_compiler_output}
     -I                       Enables retrieving contract's artifacts
                              from the EVM Contracts Source Index.
                              Default: ${index_retrieve}

  credentials options:
     -N <wallet-name>         EVM wallet name.
                              Default: ${wallet_name}
     -w <wallet-path>         EVM wallet file path.
                              Default: ${wallet_path}
     -p <wallet-password>     EVM wallet password file.
                              Default: ${wallet_password}
     -s <wallet-seed>         EVM wallet seed file.
                              Default: ${wallet_seed}
     -k <api-key>             Etherscan-like service key.
                              Default: ${api_key}

  libEVM options:
     -K                       Target application.
                              Default: ${target_app}
     -a                       Call authentication.
                              Default: ${call_auth}
     -n <network>             EVM network name. Accepted values
                              are all those supported by
                              evm-chains-info and RPC addresses.
                              Default: ${target_network}
     -S <rpc-selection>       RPC selection method. It can be
                              'kirsh' or 'random'.
                              Default: ${rpc_selection}

  application options:
     -W <cache-dir>           Cache directory
                              Default: ${cache_dir}
     -D <data-dir>            Application data directory
                              Default: ${data_dir}

     -h                       This message.
     -c                       Enable color output.
     -v                       Enable verbose output.

ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${_exit_code}"
}

_display_array() {
  local \
    _array=() \
    _item
  _array+=(
    "$@"
  )
  for _item \
    in "${_array[@]}"; do
  _msg_info \
    "                             ${_item}"
  done
}

# Shows configuration options.
_show_config() {
  local \
    _config_text=()
  _config_text+=(
    "${app_name} configuration"
    "                Call date:   ${call_date}"
    "                Call type:   ${call_type}"
    "      Call authentication:   ${call_auth}"
    "    Application options:"
    "          Cache directory:   ${cache_dir}"
    "           Data directory:   ${data_dir}"
    "    Credentials options:"
    "              Wallet name:   ${wallet_name}"
    "           Wallet address:   ${wallet_address}"
    "              Wallet path:   ${wallet_path}"
    "          Wallet password:   ${wallet_password}"
    "              Wallet seed:   ${wallet_seed}"
    "        Network options:"
    "           Target network:   ${target_network}"
    "              Max retries:   ${retries_max}"
    "             Call timeout:   ${call_timeout}"
    "                  API key:   ${api_key}"
    "     RPC selection method:   ${rpc_selection}"
    "                Gas price:   ${price_gas}"
    "       Contract options:"
    "       Target application:   ${target_app}"
    "          Target contract:   ${target_contract}"
    "         Contract address:   ${contract_address}"
    "             Contract ABI:   ${contract_abi}"
    "        Contract bytecode:   ${contract_bytecode}"
    " Contract compiler output:   ${contract_compiler_output}"
    "           Call options:"
    "            Message value:   ${msg_value}"
    "             Measure unit:   ${measure_unit}"
    "          Contract method:   ${contract_method}"
    "         Method arguments:"
  )
  for _msg in "${_config_text[@]}"; do
    _msg_info \
      "${_msg[*]}"
  done
  _display_array                          "${method_args[@]}"
}

_globals
_global_variables
_libevm_global_variables
_requirements
# shellcheck disable=SC2034
getopts_opts="$(
  printf \
    "%s" \
    "t:T:I:P:V:u:r:S:K:" \
    "A:B:C:" \
    "$(_libevm_app_getopts_params_get)" \
    "a:n:" \
    "$(_wallet_getopts_params_get)" \
    "W:D:cvh")"
while \
  getopts \
    "${getopts_opts}" \
    arg; do
  _wallet_getopts_case
  _libevm_app_getopts_case
  case \
    "${arg}" in
    t)
      override_call_type="${OPTARG}" ;;
    T)
      override_call_timeout="${OPTARG}" ;;
    I)
      override_index_retrieve="y" ;;
    P)
      override_price_gas="${OPTARG}" ;;
    V)
      override_msg_value="${OPTARG}" ;;
    u)
      override_measure_unit="${OPTARG}" ;;
    r)
      override_retries_max="${OPTARG}" ;;
    S)
      override_rpc_selection="${OPTARG}" ;;
    K)
      override_target_app="${OPTARG}" ;;
    A)
      override_contract_abi="${OPTARG}" ;;
    B)
      override_contract_bytecode="${OPTARG}" ;;
    C)
      override_contract_compiler_output="${OPTARG}" ;;
    a)
      override_call_auth="y" ;;
    n)
      override_target_network="${OPTARG}" ;;
    W)
      override_cache_dir="${OPTARG}" ;;
    D)
      override_data_dir="${OPTARG}" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h)
      _set_overrides
      _usage \
        0 ;;
    *)
      if [[ " ${getopts_opts} " != *"${arg}"* ]]; then
        _msg=(
          "Invalid argument '${arg}'."
        )
        _msg_error \
          "${_msg[*]}" \
          0
        _usage \
          1
      fi ;;
  esac
done
shift \
  $((
    OPTIND - 1 ))
if (( $# < 1 )); then
  _msg=(
    "No address given."
  )
  _msg_error \
    "${_msg[*]}" \
    0
  _set_overrides
  _usage \
    1
fi
if (( $# < 2 )); then
  _msg=(
    "No method given."
  )
  _msg_error \
    "${_msg[*]}" \
    0
  _set_overrides
  _usage \
    1
fi
if (( 0 < $# )); then
  contract_address="${1}"
fi
if (( 1 < $# )); then
  contract_method="${2}"
fi
shift \
  2
method_args=(
  "$@"
)
_set_overrides
_show_config
app_opts=(
  "${call_type}"
  "${call_timeout}"
  "${wallet_name}"
  "${wallet_path}"
  "${wallet_password}"
  "${wallet_seed}"
  "${api_key}"
  "${msg_value}"
  "${price_gas}"
  "${measure_unit}"
  "${retries_max}"
  "${target_network}"
  "${rpc_selection}"
  "${cache_dir}"
  "${data_dir}"
  "${contract_address}"
  "${contract_abi}"
  "${contract_bytecode}"
  "${contract_compiler_output}"
  "${contract_method}"
  "${method_args[@]}"
)
_evm_contract_call \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
